[package]
name = "modules_layout_and_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "main"
path = "main.rs"


[lib]
name = "lib"
path = "lib.rs"
